services:
  app_simaksi:
    container_name: app_simaksi
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db_simaksi
    networks:
      - simaksi_network
    command: >
      sh -c "npx prisma migrate deploy && npm run dev"

  db_simaksi:
    container_name: db_simaksi
    image: mysql:8.4.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simaksi
    ports:
      - "3306:3306"
    volumes:
      - db_simaksi_data:/var/lib/mysql
    networks:
      - simaksi_network

networks:
  simaksi_network:
    driver: bridge

volumes:
  db_simaksi_data: